### PR TITLE
Add cryptsetup to installer packages

### LINKED ISSUE #4: `cryptsetup` missing?
I've generated an installer with [the instructions](https://github.com/tpwrules/nixos-m1/blob/main/docs/uefi-standalone.md#kernel-and-bootstrap-installer) on this repo, and then booted into U-Boot and then the image itself off a USB drive.

However, the installation media seems to be missing `cryptsetup`, so I can't mount (nor re-format) the existing partition on my device.

Can I somehow build an image that includes the additions from this repo _and_ the default ISO installer tools?

### PR DESCRIPTION
**Pull request by WhyNotHugo**
Fixes #4

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
Oh, actually, this

**Comment by WhyNotHugo** [comment]
Well, this _is_ required, but still missing `dm-crypt` support on the built kernel.

**Comment by tpwrules** [comment]
Please also add the relevant kernel config and test to make sure you can access encrypted volumes in the installer.

**Comment by WhyNotHugo** [comment]
I've updated the PR with all the changes I needed to actually mount the volume.

**Pull request merged**
